### ISSUE TITLE
Video autoplay doesn't start over after clicking away from slide

### ISSUE THREAD

**Issue by mapk** [ellatrix/slides#10]
### Problem
When clicking into a slide with a video that has autoplay, it works great. But as soon as I click away and come back to the slide, the video is stopped where it left off. 

### Expected
I expect that when I click away and back into the slide, the video should start autoplaying from the beginning again.

**Comment by ItsJonQ** [comment]
Rough idea for solution...
(Note, making up API names)

On a `slideChange`...
* Get all `videos` via `querySelectorAll('video')`
* Loop through `videos`
* Reset time via `video.pause(); video.currentTime = 0;`
* Target 1st video
* if `autoplay`,  then `video.play()`

The above can be simplified if we assume that a slide will always have one video:

On a `slideChange`...
* Get`video` via `querySelector('video')`
* Reset time via `video.pause(); video.currentTime = 0;`
* if `autoplay`,  then `video.play()`
