### ISSUE TITLE
Fullscreen not working on Safari

### ISSUE THREAD

**Issue by AtrumGeost** [ellatrix/slides#5]
Tried to access fullscreen while running a recent test and got this error:

![Screen Shot 2019-10-21 at 6 27 24 PM](https://user-images.githubusercontent.com/3696121/67250370-ba236480-f430-11e9-8f16-2793cedf7d36.png)

Worked normally on Chrome. Ran test both on a local WP site and also on Jurassic Ninja

macOS Catalina 10.15 (19A602) | Safari Version 13.0.2 (15608.2.30.1.1)

**Comment by ellatrix** [comment]
Fixed now. Thanks!
