### ISSUE TITLE
Please add support for Presenter/Presentation Clicker

### ISSUE THREAD

**Issue by AtrumGeost** [ellatrix/slides#6]
I went into fullscreen with Chrome and tried to use a clicker, very similar to [this one](https://www.amazon.com/Wireless-Presenter-Rechargeable-Presentation-Powerpoint/dp/B07X4D73WZ/ref=sr_1_13?crid=3IVFRMNWNAP1P&keywords=presenter+clicker&qid=1571700690&sprefix=presenter%2Caps%2C225&sr=8-13).

The clicker didn't work to move forward or back. I tried with a Keynote presentation and it worked.

I'm not sure what's the "key" that the clicket uses to trigger the next or previous slide.

But it would be awesome to have support for this.

**Comment by ellatrix** [comment]
Hm, this should just work by default. What key code is https://keycode.info reporting when that page is active and you click?

**Comment by AtrumGeost** [comment]
Wow, I didn't know about that site! Looks very useful.

When I press the right button (to go forward) I get this:

![Screen Shot on 2019-10-23 at 07-35-13](https://user-images.githubusercontent.com/3696121/67393473-0de49980-f568-11e9-80df-f18cf77b8f3e.png)

And when I press the left button (to go back) I get this:

![Screen Shot on 2019-10-23 at 07-35-33](https://user-images.githubusercontent.com/3696121/67393499-22289680-f568-11e9-8cc1-5544c89162ce.png)

Then, I tested the plugin in presentation mode with the Up/Down arrows and noticed it is not working either.

So I'm guessing, right now it is only supporting the left/right arrows.

Thanks for checking this :)

**Comment by ellatrix** [comment]
Great. I can add this, no problem.
