### ISSUE TITLE
Editor styles overriden

### ISSUE THREAD

**Issue by nosolosw** [ellatrix/slides#7]
It looks like if I activate the plugin, the editor styles for Posts or Pages are also affected.

Plugin deactivated:

![Screenshot from 2019-10-24 20-49-14](https://user-images.githubusercontent.com/583546/67515883-dbd65300-f69f-11e9-9596-a7e3f064e34b.png)

Plugin activated:

![Screenshot from 2019-10-24 20-49-40](https://user-images.githubusercontent.com/583546/67515895-e1339d80-f69f-11e9-98b6-28f3588a87e0.png)

**Comment by ellatrix** [comment]
Yeah, I saw that the other day. :) This should only happen for the custom post type :D
